<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PagamentosApp.Application\PagamentosApp.Application.csproj" />
    <ProjectReference Include="..\PagamentosApp.Domain\PagamentosApp.Domain.csproj" />
  </ItemGroup>

</Project>
